default: Driver.java AdventureMap.java Room.java End.java
	javac Driver.java AdventureMap.java Room.java End.java

run: Driver.class AdventureMap.class Room.class End.class
	java Driver

clean:
	rm -f *.class